// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ExaminationDAL.Entities;

public partial class Include
{
    public int ExId { get; set; }

    public int QsId { get; set; }

    public int? StAnswer { get; set; }

    public virtual Exam Ex { get; set; } = null!;

    public virtual Question Qs { get; set; } = null!;
}