// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ExaminationDAL.Entities;

public partial class Instructor
{
    public int InsId { get; set; }

    public string? InsDegree { get; set; }

    public decimal? InsSalary { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual User Ins { get; set; } = null!;

    public virtual ICollection<Course> Crs { get; set; } = new List<Course>();

    public virtual ICollection<Department> Depts { get; set; } = new List<Department>();
}