// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ExaminationDAL.Entities;

public partial class MultipleChoice
{
    public int ChId { get; set; }

    public string? ChTitle { get; set; }

    public int? QsId { get; set; }

    public virtual Question? Qs { get; set; }
}