// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ExaminationDAL.Entities;

public partial class Topic
{
    public int TopicId { get; set; }

    public string? TopicName { get; set; }

    public int? CrsId { get; set; }

    public virtual Course? Crs { get; set; }
}