// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace ExaminationDAL.Entities;

public partial class User
{
    public int UserId { get; set; }

    public string? UserName { get; set; }

    public string? UserFname { get; set; }

    public string? UserLname { get; set; }

    public string? EmailAddress { get; set; }

    public string? Password { get; set; }

    public int? RoleId { get; set; }

    public virtual Instructor? Instructor { get; set; }

    public virtual Role? Role { get; set; }

    public virtual Student? Student { get; set; }
}